steps:
  build_app:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: git.whyservices.net
      repo: git.whyservices.net/whysthatso/vernest
      tag: ${CI_COMMIT_TAG}
      username: whysthatso
      password:
        from_secret: whysthatso_gitea_pass
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: tag
